DROP DATABASE IF EXISTS MovieDB;

CREATE DATABASE MovieDB;

USE MovieDB;

CREATE TABLE Customers(
	Id BINARY(16) PRIMARY KEY,
	`Name` VARCHAR(50) NOT NULL,
    isGold BOOLEAN DEFAULT 0,
    Phone CHAR(10) NOT NULL
);

CREATE TABLE Genres(
	Id BINARY(16) PRIMARY KEY,
	`Name` VARCHAR(50) NOT NULL
);

CREATE TABLE Movies(
	Id BINARY(16) PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
    Genre_Id BINARY(16) NOT NULL,
    Quantity INT NOT NULL,
    Daily_Rate DECIMAL(4,2) NOT NULL,
    FOREIGN KEY(Genre_Id) REFERENCES Genres(Id)
);

CREATE TABLE Rentals(
	Id BINARY(16) PRIMARY KEY,
    Movie_Id BINARY(16) NOT NULL,
    Customer_Id BINARY(16) NOT NULL,
    Rental_Date DATE NOT NULL,
    Return_Date DATE NULL,
    Fee DECIMAL(5,2) NULL,
    FOREIGN KEY(Movie_Id) REFERENCES Movies(Id),
    FOREIGN KEY(Customer_Id) REFERENCES Customers(Id)
);

CREATE TABLE Users(
	Id BINARY(16) PRIMARY KEY,
    Username VARCHAR(100) UNIQUE NOT NULL,
    `Password` VARCHAR(255) NOT NULL
);

CREATE TABLE Roles(
	Id BINARY(16) PRIMARY KEY,
	Authority VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Users_Roles(
	User_Id BINARY(16)  NOT NULL,
    Role_Id BINARY(16)  NOT NULL,
    PRIMARY KEY(User_Id,Role_Id),
	FOREIGN KEY(User_Id) REFERENCES Users(Id),
	FOREIGN KEY(Role_Id) REFERENCES Roles(Id)
);